// <auto-generated />
using IA.inteligencia_artificial.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IA.inteligencia_artificial.DataAccess.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20190327234353_App")]
    partial class App
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Models.Problema", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .HasMaxLength(100);

                    b.Property<long>("ProjetoId");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Problemas");
                });

            modelBuilder.Entity("Models.ProblemaVariavel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ProblemaId");

                    b.Property<long>("VariavelId");

                    b.HasKey("Id");

                    b.HasIndex("ProblemaId");

                    b.HasIndex("VariavelId");

                    b.ToTable("ProblemasVariaveis");
                });

            modelBuilder.Entity("Models.Projeto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome")
                        .HasMaxLength(100);

                    b.Property<string>("Responsaveis");

                    b.HasKey("Id");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("Models.Variavel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .HasMaxLength(100);

                    b.Property<long>("ProjetoId");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Variaveis");
                });

            modelBuilder.Entity("Models.Problema", b =>
                {
                    b.HasOne("Models.Projeto", "Projeto")
                        .WithMany("Problemas")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.ProblemaVariavel", b =>
                {
                    b.HasOne("Models.Problema", "Problema")
                        .WithMany("ProblemasVariaveis")
                        .HasForeignKey("ProblemaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.Variavel", "Varivavel")
                        .WithMany("ProblemasVariaveis")
                        .HasForeignKey("VariavelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Variavel", b =>
                {
                    b.HasOne("Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
